<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsRoslynComponent>true</IsRoslynComponent>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.Common">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <IncludeBuildOutput>false</IncludeBuildOutput>
  </PropertyGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Release'">
    <ProjectReference Include="..\CodeGenerators.Shared\CodeGenerators.Shared.csproj" PrivateAssets="all" />
    <None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
    <None Include="$(OutputPath)\CodeGenerators.Shared.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <ProjectReference Include="..\CodeGenerators.Shared\CodeGenerators.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <GetTargetPathDependsOn>$(GetTargetPathDependsOn);CodeGenetators_Shared_GetTargetPathDependsOn</GetTargetPathDependsOn>
  </PropertyGroup>

  <Target Name="CodeGenetators_Shared_GetTargetPathDependsOn">
    <ItemGroup>
      <TargetPathWithTargetPlatformMoniker Include="$(TargetDir)\CodeGenerators.Shared.dll" IncludeRuntimeDependency="false" />
    </ItemGroup>
  </Target>

</Project>
