namespace CodeGenerators.ValueObjects
{
    using System.Collections.Immutable;
    using System.Diagnostics;
    using System.Linq;
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp;
    using Microsoft.CodeAnalysis.CSharp.Syntax;
    using Microsoft.CodeAnalysis.Text;
    using CodeGenerators.Shared;
    using CodeGenerators.ValueObjects.Models;

    /// <inheritdoc />
    [Generator]
    public class ValueObjectsGenerator : IIncrementalGenerator
    {
        private const string ComparableValueObjectAttributeFullName = "CodeGenerators.Utils.Attributes.ComparableValueObjectAttribute";
        private const string FinalStatusAttribute = "FinalStatus";
        private const string InternalEnumName = "RealEnum";
        private const string NumericType = "int";

        private static volatile int enumValueObjectCounter = 0;
        private static volatile int valueObjectCounter = 0;

        private static readonly string[] PadLvl = Enumerable.Range(0, 6).Select(x => new string(' ', x * 4)).ToArray();

        private static TemplateManager TemplateManager { get; } = new TemplateManager();

        /// <inheritdoc />
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var pipeline = context.SyntaxProvider.CreateSyntaxProvider(IsPartialClassOfEnumValueObject, SelectEnumValueObjectDescriptor)
                .Collect()
                .Combine(context.SyntaxProvider.ForAttributeWithMetadataName(ComparableValueObjectAttributeFullName,
                        IsPartialClassOfValueObject,
                        SelectValueObjectDescriptor
                    )
                    .Collect()
                );

            context.RegisterSourceOutput(pipeline, Build);
        }

        private void Build(SourceProductionContext context, (ImmutableArray<EnumValueObjectDescriptor>, ImmutableArray<ValueObjectDescriptor>) pipeline)
        {
            var (enumValueObjects, valueObjects) = pipeline;

            GenerateEnumValueObjects(context, enumValueObjects);
            GenerateValueObjects(context, valueObjects);
        }

        private static void GenerateEnumValueObjects(SourceProductionContext context, ImmutableArray<EnumValueObjectDescriptor> source)
        {
            foreach (var descriptor in source)
            {
                context.SafeGenerate(descriptor.Location,
                    descriptor.ClassName,
                    () => GenerateEnumValueObjectFile(context, descriptor));
            }
        }

        private static void GenerateValueObjects(SourceProductionContext context, ImmutableArray<ValueObjectDescriptor> source)
        {
            foreach (var descriptor in source)
            {
                context.SafeGenerate(descriptor.Location,
                    descriptor.ClassName,
                    () => GenerateValueObjectFile(context, descriptor));
            }
        }

        private static void GenerateEnumValueObjectFile(SourceProductionContext context, EnumValueObjectDescriptor classDescriptor)
        {
            var count = Interlocked.Increment(ref enumValueObjectCounter);

            var header = @$"// <auto-generated/>
// Count: {count}
";
            var sb = new StringBuilder(header + TemplateManager.EnumValueObject);

            var ns = classDescriptor.Namespace;
            var className = classDescriptor.ClassName;
            var parseStrBody = new StringBuilder();
            var parseNumBody = new StringBuilder();
            var parseEnumBody = new StringBuilder();
            var enumBody = new StringBuilder();
            var finalStatusBody = new StringBuilder();
            var possibleValues = new StringBuilder();

            foreach (var property in classDescriptor.Properties)
            {
                var name = property.Name;
                var value = property.Value;
                var propertyName = property.PropertyName;

                parseStrBody.AppendLine($"{PadLvl[3]}if (string.Equals(strValue, {name}, StringComparison.OrdinalIgnoreCase)) return {propertyName};");
                parseNumBody.AppendLine($"{PadLvl[3]}if (numValue == {value}) return {propertyName};");
                parseEnumBody.AppendLine($"{PadLvl[4]}case {className}.{InternalEnumName}.{propertyName}: return {propertyName};");
                enumBody.AppendLine($"{PadLvl[3]}{propertyName} = {value},");
                possibleValues.AppendLine($"{value} ({propertyName})");
                if (property.IsFinal)
                {
                    finalStatusBody.AppendLine($"{PadLvl[4]}case {value}:");
                }
            }

            if (finalStatusBody.Length > 0)
            {
                finalStatusBody.AppendLine($"{PadLvl[5]}return true;");
            }

            sb.Replace(TemplateManager.NamespaceMarker, ns);
            sb.Replace(TemplateManager.ClassNameMarker, className);
            sb.Replace("TEMPLATE_EnumBody", enumBody.ToString());
            sb.Replace("TEMPLATE_PossibleValues", possibleValues.ToString().TrimEnd());
            sb.Replace("TEMPLATE_InternalEnumName", InternalEnumName);
            sb.Replace("TEMPLATE_NumericType", NumericType);
            sb.Replace("TEMPLATE_NumberParseBody", parseNumBody.ToString());
            sb.Replace("TEMPLATE_StringParseBody", parseStrBody.ToString());
            sb.Replace("TEMPLATE_EnumParseBody", parseEnumBody.ToString());
            sb.Replace("TEMPLATE_IsFinalBody", finalStatusBody.ToString());

            context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static void GenerateValueObjectFile(SourceProductionContext context, ValueObjectDescriptor classDescriptor)
        {
            var count = Interlocked.Increment(ref valueObjectCounter);
            var header = @$"// <auto-generated/>
// Count: {count}
";
            var sb = new StringBuilder(header + TemplateManager.Comparable);

            var ns = classDescriptor.Namespace;
            var className = classDescriptor.ClassName;

            sb.Replace(TemplateManager.NamespaceMarker, ns);
            sb.Replace(TemplateManager.ClassNameMarker, className);

            context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private bool IsPartialClassOfEnumValueObject(SyntaxNode node, CancellationToken token)
        {
            return node is ClassDeclarationSyntax { Parent: BaseNamespaceDeclarationSyntax, BaseList: not null } classDeclaration
                && classDeclaration.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.PartialKeyword)
                    && classDeclaration.BaseList.Types.Any(baseType => baseType.ToString().EndsWith("EnumValueObject")));
        }

        private bool IsPartialClassOfValueObject(SyntaxNode node, CancellationToken token)
        {
            return node is ClassDeclarationSyntax { Parent: BaseNamespaceDeclarationSyntax, BaseList: not null } classDeclaration
                && classDeclaration.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.PartialKeyword));
        }

        private static EnumValueObjectDescriptor SelectEnumValueObjectDescriptor(GeneratorSyntaxContext syntaxContext, CancellationToken cancellationToken)
        {
            if (syntaxContext.Node is ClassDeclarationSyntax { Parent: BaseNamespaceDeclarationSyntax namespaceNode } classDeclaration)
            {
                var ns = namespaceNode.Name.ToString();
                var className = classDeclaration.Identifier.ToString();
#if DEBUG
                if (className == "DebugClassEnumValueObject")
                {
                    Debugger.Break();
                }
#endif
                var properties = classDeclaration.Members.OfType<PropertyDeclarationSyntax>()
                    .Where(x => x.Initializer != null)
                    .Select(p =>
                    {
                        var argList = p.Initializer!.ChildNodes()
                            .OfType<BaseObjectCreationExpressionSyntax>()
                            .First()
                            .ArgumentList!.Arguments;
                        var isFinal = p.AttributeLists.Any(z => z.Attributes.Any(a => a.ToString().Contains(FinalStatusAttribute)));

                        var name = argList[0].NameColon == null
                            ? argList[0].ToString()
                            : "default";
                        var value = argList[1].NameColon == null
                            ? argList[1].ToString()
                            : "default";

                        return new EnumValueObjectPropertyDescriptor(p.Identifier.ToString(), name, value, isFinal);
                    })
                    .ToImmutableArray();

                return new EnumValueObjectDescriptor(ns, className, properties, classDeclaration.Identifier.GetLocation());
            }

            Debugger.Break();

            throw new InvalidOperationException();
        }

        private static ValueObjectDescriptor SelectValueObjectDescriptor(GeneratorAttributeSyntaxContext syntaxContext, CancellationToken cancellationToken)
        {
            if (syntaxContext.TargetNode is ClassDeclarationSyntax { Parent: BaseNamespaceDeclarationSyntax namespaceNode } classDeclaration)
            {
                var ns = namespaceNode.Name.ToString();
                var className = classDeclaration.Identifier.ToString();
#if DEBUG
                if (className == "DebugClassValueObject")
                {
                    Debugger.Break();
                }
#endif
                return new ValueObjectDescriptor(ns, className, classDeclaration.Identifier.GetLocation());
            }

            Debugger.Break();

            throw new InvalidOperationException();
        }
    }
}