namespace CodeGenerators.ValueObjects
{
    using System.Collections.Immutable;
    using System.Diagnostics;
    using System.Linq;
    using System.Text;
    using Microsoft.CodeAnalysis;
    using Microsoft.CodeAnalysis.CSharp;
    using Microsoft.CodeAnalysis.CSharp.Syntax;
    using Microsoft.CodeAnalysis.Text;
    using CodeGenerators.Shared;
    using CodeGenerators.ValueObjects.Models;

    /// <inheritdoc />
    [Generator]
    public class ValueObjectsGenerator : IIncrementalGenerator
    {
        private const string ComparableValueObjectAttributeFullName = "CodeGenerators.Utils.Attributes.ComparableValueObjectAttribute";
        private const string FinalStatusAttribute = "FinalStatus";
        private const string  EnumName = "Enum";
        private const string  NumericType = "int";

        private static volatile int enumValueObjectCounter = 0;
        private static volatile int valueObjectCounter = 0;

        private static readonly string[] PadLvl = Enumerable.Range(0, 6).Select(x => new string(' ', x * 4)).ToArray();

        /// <inheritdoc />
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var pipeline = context.SyntaxProvider.CreateSyntaxProvider(IsPartialClassOfEnumValueObject, SelectEnumValueObjectDescriptor)
                .Collect()
                .Combine(context.SyntaxProvider.ForAttributeWithMetadataName(ComparableValueObjectAttributeFullName,
                        IsPartialClassOfValueObject,
                        SelectValueObjectDescriptor
                    )
                    .Collect()
                );

            context.RegisterSourceOutput(pipeline, Build);
        }

        private void Build(SourceProductionContext context, (ImmutableArray<EnumValueObjectDescriptor>, ImmutableArray<ValueObjectDescriptor>) pipeline)
        {
            var (enumValueObjects, valueObjects) = pipeline;

            GenerateEnumValueObjects(context, enumValueObjects);
            GenerateValueObjects(context, valueObjects);
        }

        private static void GenerateEnumValueObjects(SourceProductionContext context, ImmutableArray<EnumValueObjectDescriptor> source)
        {
            foreach (var descriptor in source)
            {
                context.SafeGenerate(descriptor.Location,
                    descriptor.ClassName,
                    () => GenerateEnumValueObjectFile(context, descriptor));
            }
        }

        private static void GenerateValueObjects(SourceProductionContext context, ImmutableArray<ValueObjectDescriptor> source)
        {
            foreach (var descriptor in source)
            {
                context.SafeGenerate(descriptor.Location,
                    descriptor.ClassName,
                    () => GenerateValueObjectFile(context, descriptor));
            }
        }

        private static void GenerateEnumValueObjectFile(SourceProductionContext context, EnumValueObjectDescriptor classDescriptor)
        {
            var count = Interlocked.Increment(ref enumValueObjectCounter);
            var sb = new StringBuilder();
            sb.Append(@$"// <auto-generated/>
// Count: {count}
#nullable enable
#pragma warning disable CS0660, CS0661
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq.Expressions;
using CodeGenerators.Utils;
");
            var ns = classDescriptor.Namespace;
            var className = classDescriptor.ClassName;
            var parseStrBody = new StringBuilder();
            var parseNumBody = new StringBuilder();
            var parseEnumBody = new StringBuilder();
            var enumBody = new StringBuilder();
            var finalStatusBody = new StringBuilder();
            var possibleValues = new StringBuilder();

            foreach (var property in classDescriptor.Properties)
            {
                var name = property.Name;
                var value = property.Value;
                var propertyName = property.PropertyName;

                parseStrBody.AppendLine($"{PadLvl[3]}if (string.Equals(strValue, {name}, StringComparison.OrdinalIgnoreCase)) return {propertyName};");
                parseNumBody.AppendLine($"{PadLvl[3]}if (numValue == {value}) return {propertyName};");
                parseEnumBody.AppendLine($"{PadLvl[4]}case {className}.{EnumName}.{propertyName}: return {propertyName};");
                enumBody.AppendLine($"{PadLvl[3]}{propertyName} = {value},");
                possibleValues.AppendLine($"{value} ({propertyName})");
                finalStatusBody.AppendLine($"{PadLvl[4]}case {value}: return {property.IsFinal.ToString().ToLower()};");
            }

            var isFinalStatus = new StringBuilder();
            if (classDescriptor.Properties.Any(z => z.IsFinal))
            {
                isFinalStatus.Append(IsFinalStatusMethod);
                isFinalStatus.Replace("[PLACEHOLDER]", finalStatusBody.ToString());
            }

            sb.AppendLine(@$"namespace {ns}
{{
    partial class {className} : IEnumValueObjectParser<{className}>,
        IHavePossibleValues,
        IEqualityComparer<{className}>,
        IEquatable<{className}>
    {{
        public enum {EnumName} : {NumericType}
        {{
{enumBody}
        }}

        public {EnumName} ToEnum()
        {{
            return ({EnumName})this.Value;
        }}

        /// <inheritdoc />
        public static string PossibleValues {{ get; }} = @""{possibleValues.ToString().TrimEnd()}"";

        /// <inheritdoc />
        public static Expression<Func<{NumericType}?, {className}?>> TryParseExpression {{ get; }} = x => {className}.TryParse(x);

        /// <summary>
        /// Получить экземпляр <see cref=""{className}""/> из числового значения
        /// </summary>
        /// <param name=""numValue"">Числовое значение</param>
        /// <exception cref=""ArgumentNullException"">Значение равно null</exception>
        /// <exception cref=""ArgumentOutOfRangeException"">Значение не определено</exception>
        [return: NotNullIfNotNull(nameof(numValue))]
        public static {className} Parse([NotNull]{NumericType}? numValue)
        {{
            if (numValue == null)
            {{
                throw new ArgumentNullException(nameof(numValue), ""Значение равно null"");
            }}

{parseNumBody}
            throw new ArgumentOutOfRangeException(nameof(numValue), ""Значение не определено"");
        }}

        /// <summary>
        /// Получить экземпляр <see cref=""{className}""/> из строкового значения
        /// </summary>
        /// <param name=""strValue"">Строковое значение</param>
        /// <exception cref=""ArgumentNullException"">Значение равно null</exception>
        /// <exception cref=""ArgumentOutOfRangeException"">Значение не определено</exception>
        [return: NotNullIfNotNull(nameof(strValue))]
        public static {className} Parse([NotNull]string? strValue)
        {{
            if (strValue == null)
            {{
                throw new ArgumentNullException(nameof(strValue), ""Значение равно null"");
            }}

{parseStrBody}
            throw new ArgumentOutOfRangeException(nameof(strValue), ""Значение не определено"");
        }}

        /// <summary>
        /// Получить экземпляр <see cref=""{className}""/> из <see cref=""{className}.{EnumName}""/>
        /// </summary>
        /// <param name=""enumValue"">Значение перечисления</param>
        /// <exception cref=""ArgumentNullException"">Значение равно null</exception>
        /// <exception cref=""ArgumentOutOfRangeException"">Значение не определено</exception>
        [return: NotNullIfNotNull(nameof(enumValue))]
        public static {className} Parse([NotNull]{className}.{EnumName}? enumValue)
        {{
            if (enumValue == null)
            {{
                throw new ArgumentNullException(nameof(enumValue), ""Значение равно null"");
            }}
            switch(enumValue)
            {{
{parseEnumBody}
                default:
                    throw new ArgumentOutOfRangeException(nameof(enumValue), ""Значение не определено"");
            }}
        }}

        /// <summary>
        /// Получить экземпляр <see cref=""{className}""/> из числового значения
        /// </summary>
        /// <param name=""numValue"">Числовое значение</param>
        public static {className}? TryParse({NumericType}? numValue)
        {{
            if (numValue == null)
            {{
                return null;
            }}
            try
            {{
                return Parse(numValue);
            }}
            catch(ArgumentOutOfRangeException)
            {{
                // ignore
            }}
            return null;
        }}

        /// <summary>
        /// Получить экземпляр <see cref=""{className}""/> из строкового значения
        /// </summary>
        /// <param name=""strValue"">Строковое значение</param>
        public static {className}? TryParse(string? strValue)
        {{
            if (strValue == null)
            {{
                return null;
            }}
            try
            {{
                return Parse(strValue);
            }}
            catch(ArgumentOutOfRangeException)
            {{
                // ignore
            }}
            return null;
        }}
{isFinalStatus}
        /// <inheritdoc />
        public override bool Equals(object? obj)
        {{
            return InternalEquals(this, obj as {className});
        }}

        /// <inheritdoc />
        public override int GetHashCode()
        {{
            return Value.GetHashCode();
        }}

        private static bool InternalEquals({className}? left, {className}? right)
        {{
            if (ReferenceEquals(left, right)) return true;
            if (left is null || right is null) return false;

            return left.Value == right.Value;
        }}

        public static bool operator ==({className}? left, {className}? right)
        {{
            // ReSharper disable once ArrangeStaticMemberQualifier
            return {className}.InternalEquals(left, right);
        }}

        public static bool operator !=({className}? left, {className}? right)
        {{
            // ReSharper disable once ArrangeStaticMemberQualifier
            return !{className}.InternalEquals(left, right);
        }}

        /// <inheritdoc />
        public bool Equals({className}? other)
        {{
            return InternalEquals(this, other);
        }}

        /// <inheritdoc />
        public bool Equals({className}? x, {className}? y)
        {{
            return InternalEquals(x, y);
        }}

        /// <inheritdoc />
        public int GetHashCode({className} obj)
        {{
            return obj.Value.GetHashCode();
        }}
    }}
}}");

            context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private static void GenerateValueObjectFile(SourceProductionContext context, ValueObjectDescriptor classDescriptor)
        {
            var count = Interlocked.Increment(ref valueObjectCounter);
            var sb = new StringBuilder();
            sb.Append(@$"// <auto-generated/>
// Count: {count}
#nullable enable
#pragma warning disable CS0660, CS0661
using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using CodeGenerators.Utils;
");
            var ns = classDescriptor.Namespace;
            var className = classDescriptor.ClassName;

            sb.AppendLine(@$"namespace {ns}
{{
    partial class {className} :
        IEquatable<{className}>,
        IEqualityComparer<{className}>,
        IComparable<{className}>,
        IComparable
    {{
        private static bool InternalEquals({className}? left, {className}? right)
        {{
            if (ReferenceEquals(left, right))
            {{
                return true;
            }}
            if (left is null || right is null || left.GetType() != right.GetType())
            {{
                return false;
            }}

            return left.Value == right.Value;
        }}

        private static int InternalCompare({className}? left, {className}? right)
        {{
            if (ReferenceEquals(left, right))
            {{
                return 0;
            }}
            if (right is null)
            {{
                return 1;
            }}
            if (left is null)
            {{
                return -1;
            }}

            return left.Value.CompareTo(right.Value);
        }}

        /// <inheritdoc />
        public override bool Equals(object? obj)
        {{
            return InternalEquals(this, obj as {className});
        }}

        /// <inheritdoc />
        public override int GetHashCode()
        {{
            return Value.GetHashCode();
        }}

        /// <inheritdoc />
        public int CompareTo({className}? other)
        {{
            if (other is null)
            {{
                return 1;
            }}

            return this.Value.CompareTo(other.Value);
        }}

        /// <inheritdoc />
        public int CompareTo(object? obj)
        {{
            return CompareTo(obj as {className});
        }}

        /// <inheritdoc />
        public bool Equals({className}? other)
        {{
            return InternalEquals(this, other);
        }}

        /// <inheritdoc />
        public bool Equals({className}? x, {className}? y)
        {{
            return InternalEquals(x, y);
        }}

        /// <inheritdoc />
        public int GetHashCode({className} obj)
        {{
            return obj.Value.GetHashCode();
        }}

        public static bool operator ==({className}? left, {className}? right)
        {{
            return InternalEquals(left, right);
        }}

        public static bool operator !=({className}? left, {className}? right)
        {{
            return !InternalEquals(left, right);
        }}

        public static bool operator <({className}? left, {className}? right)
        {{
            return InternalCompare(left, right) < 0;
        }}
        public static bool operator <=({className}? left, {className}? right)
        {{
            return InternalCompare(left, right) <= 0;
        }}

        public static bool operator >({className}? left, {className}? right)
        {{
            return InternalCompare(left, right) > 0;
        }}

        public static bool operator >=({className}? left, {className}? right)
        {{
            return InternalCompare(left, right) >= 0;
        }}
    }}
}}");

            context.AddSource($"{className}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
        }

        private bool IsPartialClassOfEnumValueObject(SyntaxNode node, CancellationToken token)
        {
            return node is ClassDeclarationSyntax { Parent: BaseNamespaceDeclarationSyntax, BaseList: not null } classDeclaration
                && classDeclaration.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.PartialKeyword)
                    && classDeclaration.BaseList.Types.Any(baseType => baseType.ToString().EndsWith("EnumValueObject")));
        }

        private bool IsPartialClassOfValueObject(SyntaxNode node, CancellationToken token)
        {
            return node is ClassDeclarationSyntax { Parent: BaseNamespaceDeclarationSyntax, BaseList: not null } classDeclaration
                && classDeclaration.Modifiers.Any(modifier => modifier.IsKind(SyntaxKind.PartialKeyword));
        }

        private static EnumValueObjectDescriptor SelectEnumValueObjectDescriptor(GeneratorSyntaxContext syntaxContext, CancellationToken cancellationToken)
        {
            if (syntaxContext.Node is ClassDeclarationSyntax { Parent: BaseNamespaceDeclarationSyntax namespaceNode } classDeclaration)
            {
                var ns = namespaceNode.Name.ToString();
                var className = classDeclaration.Identifier.ToString();
                if (className == "DebugClassEnumValueObject")
                {
                    Debugger.Break();
                }

                var properties = classDeclaration.Members.OfType<PropertyDeclarationSyntax>()
                    .Where(x => x.Initializer != null)
                    .Select(p =>
                    {
                        var argList = p.Initializer!.ChildNodes()
                            .OfType<BaseObjectCreationExpressionSyntax>()
                            .First()
                            .ArgumentList!.Arguments;
                        var isFinal = p.AttributeLists.Any(z => z.Attributes.Any(a => a.ToString().Contains(FinalStatusAttribute)));

                        var name = argList[0].NameColon == null
                            ? argList[0].ToString()
                            : "default";
                        var value = argList[1].NameColon == null
                            ? argList[1].ToString()
                            : "default";

                        return new EnumValueObjectPropertyDescriptor(p.Identifier.ToString(), name, value, isFinal);
                    })
                    .ToImmutableArray();

                return new EnumValueObjectDescriptor(ns, className, properties, classDeclaration.Identifier.GetLocation());
            }

            Debugger.Break();

            throw new InvalidOperationException();
        }

        private static ValueObjectDescriptor SelectValueObjectDescriptor(GeneratorAttributeSyntaxContext syntaxContext, CancellationToken cancellationToken)
        {
            if (syntaxContext.TargetNode is ClassDeclarationSyntax { Parent: BaseNamespaceDeclarationSyntax namespaceNode } classDeclaration)
            {
                var ns = namespaceNode.Name.ToString();
                var className = classDeclaration.Identifier.ToString();
                if (className == "DebugClassValueObject")
                {
                    Debugger.Break();
                }

                return new ValueObjectDescriptor(ns, className, classDeclaration.Identifier.GetLocation());
            }

            Debugger.Break();

            throw new InvalidOperationException();
        }

        private const string IsFinalStatusMethod = @"
        /// <inheritdoc />
        public override bool IsFinal()
        {
            switch(this.Value)
            {
[PLACEHOLDER]
            }
            return false;
        }
";
    }
}