<Project>
  <PropertyGroup>
    <ExtensionsVersion>8.0.0</ExtensionsVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="$(ExtensionsVersion)" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="$(ExtensionsVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Abstractions" Version="$(ExtensionsVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="$(ExtensionsVersion)" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="$(ExtensionsVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="$(ExtensionsVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="$(ExtensionsVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Localization" Version="$(ExtensionsVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="$(ExtensionsVersion)" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="$(ExtensionsVersion)" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="$(ExtensionsVersion)" />
    <PackageVersion Include="System.Text.Json" Version="$(ExtensionsVersion)" />
  </ItemGroup>
</Project>