<Project>
  <Import Project="..\Nuget.Build.props"/>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>

    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>

    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

</Project>